<a href="https://colab.research.google.com/github/jiaweili176/LIJIAWIE66/blob/main/2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
shape = (3, 3, 6)
three_D_array = np.random.randint(0, 21, shape)
print(three_D_array)
print('배열의 shape:', three_D_array.shape)

[[[ 7 10 15  9 19  6]
  [ 3 17  6  4 10  5]
  [ 9  2 15 19  2  9]]

 [[18 18  5  3  4 19]
  [ 6  5  4  9  5 17]
  [ 6 18  4 18 13  4]]

 [[ 2  2 15  2 10 10]
  [18  2  8  7  7 12]
  [18 20 17  8  9  9]]]
배열의 shape: (3, 3, 6)


In [2]:
import numpy as np
shape = (5, 6)
two_D_array = np.random.randint(0, 101, shape)
print(two_D_array)
print('배열의 shape:', two_D_array.shape)

[[ 77  46  37  17  48  32]
 [ 36   8  70  75 100  50]
 [ 67  19  17  29  50  48]
 [ 68  98  59  99  48  42]
 [ 83  89  79  38  60  40]]
배열의 shape: (5, 6)


In [3]:
import numpy as np
temp = np.arange(48)
print('Original 1D Array temp shape:', temp.shape)

# 生成三维数组
three_D_array = temp.reshape(4, 3, 4)
print('\nReshaped 3D Array (4, 3, 4):')
print(three_D_array)
print('Shape of 3D array:', three_D_array.shape)

# 生成二维数组
two_D_array = temp.reshape(6, 8)
print('\nReshaped 2D Array (6, 8):')
print(two_D_array)
print('Shape of 2D array:', two_D_array.shape)

Original 1D Array temp shape: (48,)

Reshaped 3D Array (4, 3, 4):
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]

 [[24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]]

 [[36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]
Shape of 3D array: (4, 3, 4)

Reshaped 2D Array (6, 8):
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]]
Shape of 2D array: (6, 8)
